#!/bin/bash

# Copyright 2024 IBM Corporation and others.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

_gr_complete() {
    _sort() { env LC_ALL=C sort; }
    _spin() (
        s='-\|/'
        pid=$!
        i=0
        printf "\n  %s ..." "$1"
        while kill -0 $pid 2>/dev/null; do
            i=$(( (i+1)%4 ));
            printf "\r${s:$i:1}";
            sleep .1;
        done
        echo
    ) >&2
    if type -t gsed > /dev/null; then _sed() { gsed "$@"; }; else _sed() { sed "$@"; }; fi
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local cache_dir="$HOME/.gr_tabcomplete"
    mkdir -p "$cache_dir"

    local chksum="no_gradle_files"
    [ ! -f build.gradle ] || chksum="$(find . -name build.gradle |_sort |tar -cf - -T - --owner=0 --group=0 |md5sum |cut -d ' ' -f 1)"
    local cache_file="$cache_dir/$chksum"
    local commands
    if [ -f "$cache_file" ]; then
        commands="$(cat "$cache_file")"
    else
        commands="$(gr --quiet tasks |_sed -ne '/^Tasks runnable /,/To see all tasks/ p' |grep -E '^[^ ]+( - .*)?$' |grep -v '^-*$' |cut -d ' ' -f 1 |_sort & _spin "Finding gr tasks")"
        { [ "$commands" ] && echo "$commands" > "$cache_file"; } || echo "Unable to determine gr tasks :(" >&2
    fi
    COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
    unset -f _sort _spin _sed
}
complete -F _gr_complete gr
